### ISSUE TITLE
Pre-commit hook appears execute after commit has taken place

### ISSUE THREAD

**Issue by joeapearson** [qgadrian/elixir_git_hooks#74]
Hi.

I have my project set up similarly to that described in `README.md`:

```elixir
if Mix.env() != :prod do
  config :git_hooks,
    auto_install: true,
    verbose: true,
    hooks: [
      pre_commit: [
        tasks: [
          {:cmd, "mix format"}
        ]
      ],
      pre_push: [
        tasks: [
          {:cmd, "mix credo --strict"},
          {:cmd, "mix dialyzer"},
          {:cmd, "mix test"}
        ]
      ],
      post_checkout: [
        tasks: [
          {:cmd, "mix deps.get"}
        ]
      ]
    ]
end
```

The `pre_push` and `post_checkout` hooks work fine.

The `pre_commit` hook does execute, but it executes _after_ the commit has taken place.  What I then end up with is:

1. A commit with unformatted files in it
2. A bunch of staged changes with formatted files

Any ideas what I'm doing wrongly?  Is this a bug?  If so any extra information I can gather?

**Comment by qgadrian** [comment]
> Hi.
> 
> I have my project set up similarly to that described in `README.md`:
> 
> ```elixir
> if Mix.env() != :prod do
>   config :git_hooks,
>     auto_install: true,
>     verbose: true,
>     hooks: [
>       pre_commit: [
>         tasks: [
>           {:cmd, "mix format"}
>         ]
>       ],
>       pre_push: [
>         tasks: [
>           {:cmd, "mix credo --strict"},
>           {:cmd, "mix dialyzer"},
>           {:cmd, "mix test"}
>         ]
>       ],
>       post_checkout: [
>         tasks: [
>           {:cmd, "mix deps.get"}
>         ]
>       ]
>     ]
> end
> ```
> 
> The `pre_push` and `post_checkout` hooks work fine.
> 
> The `pre_commit` hook does execute, but it executes _after_ the commit has taken place. What I then end up with is:
> 
>     1. A commit with unformatted files in it
> 
>     2. A bunch of staged changes with formatted files
> 
> 
> Any ideas what I'm doing wrongly? Is this a bug? If so any extra information I can gather?

Hey @joeapearson, I believe you are using it wrong. The `pre commit` hook will format your files, but it won't stage them when creating the commit. In this case, you might want to create a script that will format and stage the files as well? I'm not 100% sure that would work but you can give it a try.

Since I want to know what is going to be staged, I use `{:cmd, "mix format --check-formatted"}` instead. If the files are not formatted the commit will be aborted and you can stage the changes.

**Comment by joeapearson** [comment]
@qgadrian thanks for the reply.  I'll give it a go!

**Comment by qgadrian** [comment]
> @qgadrian thanks for the reply. I'll give it a go!

Awesome, I will close this issue now but ping me if you have any problem or have any other questions ☺️

**Comment by joeapearson** [comment]
My only feedback is that it was counter-intuitive for me personally... but that's just me!  I can appreciate that a distinction between the "pre-commit" and "staging of changes" step is powerful.  I wonder if that could even be a feature request.

**Comment by qgadrian** [comment]
> My only feedback is that it was counter-intuitive for me personally... but that's just me! I can appreciate that a distinction between the "pre-commit" and "staging of changes" step is powerful. I wonder if that could even be a feature request.

Yeah, I updated the README to avoid expectations of auto format & commit although [it's nothing related to this library](https://github.com/pre-commit/pre-commit/issues/747#issuecomment-386782080) at all. Anyway, [seems that you could run `git add -u && !!`](https://github.com/pre-commit/pre-commit/issues/806) as well after the commit, but it will be _at your own risk_.

**Comment by joeapearson** [comment]
Thanks for the suggestions.  `git add -u && !!` might be a little heavy for me... I also found https://prettier.io/docs/en/precommit.html#option-5-shell-script which seems could be easily adapted.

**Comment by qgadrian** [comment]
> Thanks for the suggestions. `git add -u && !!` might be a little heavy for me... I also found [prettier.io/docs/en/precommit.html#option-5-shell-script](https://prettier.io/docs/en/precommit.html#option-5-shell-script) which seems could be easily adapted. (But since I need to support both Windows and Unix style systems, I would need to do some extra work to make that happen. For a rainy day!)

Awesome! If you make it work you can share it here and I will link it from the README for reference, or you can contribute with a PR as well. Good luck and have fun! 💪💪💪

**Comment by joeapearson** [comment]
Thanks will do!  Also thanks for the super fast replies and useful library.

**Comment by asmodehn** [comment]
Hi,

I encountered a similar "issue", meaning I didn't expect it to commit files when there were format-related changes done to the files.

I m guessing mostly because the behavior here differs from a similar tool I use in python land:
- pre-commit
- black

The behavior there, is that the commit will abort if there are files that have been formatted (preventing to commit unformatted file).
The user should then stage the formatting modifications to git for commit, or explicitly ignore them and commit the files as they were previously, keeping the formatting changes in the worktree only.

It is safe because committing unformatted file is an explicit user action.
And it automatically calls the formatting for a user, (one less task to run repeatedly from the shell).

Would it be feasible to get the same behavior with elixir_git_hooks ?

**Comment by qgadrian** [comment]
> Hi,
> 
> I encountered a similar "issue", meaning I didn't expect it to commit files when there were format-related changes done to the files.
> 
> I m guessing mostly because the behavior here differs from a similar tool I use in python land:
> 
>     * pre-commit
> 
>     * black
> 
> 
> The behavior there, is that the commit will abort if there are files that have been formatted (preventing to commit unformatted file).
> The user should then stage the formatting modifications to git for commit, or explicitly ignore them and commit the files as they were previously, keeping the formatting changes in the worktree only.
> 
> It is safe because committing unformatted file is an explicit user action.
> And it automatically calls the formatting for a user, (one less task to run repeatedly from the shell).
> 
> Would it be feasible to get the same behavior with elixir_git_hooks ?

Hi @asmodehn!

If you execute `mix format --check-formatted` in your hooks configuration, the `pre-commit` hook will throw an error and you won't be able to commit the changes.

There is a _special situation_ where you have the files formatted but not staged yet. In that case, the hook won't throw an error, since it will just use the local state to run the checks. You can work around this by configuring `elixir_git_hooks` to run a script that, for example:

* stash the changes
* run the necessary actions
* unstash the changes again

I don't like this approach since I don't like to have any automated actions on the tree project, so never tried it.
